[package]
name = "palette_generator"
version = "0.1.0"
authors = ["Vesa Ihanainen"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.9"
rand = "0.7.3"
kdtree = "0.5.1"
